# Generated by Django 5.2.13 on 2026-05-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('departmentID', models.IntegerField()),
            ],
        ),
    ]
